version: '3.8'
services:
  astack:
    build: .
    container_name: astack_app
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"
    tty: true
    environment:
      - NODE_ENV=development

  db:
    image: postgres:16
    container_name: astack_db
    environment:
      POSTGRES_USER: astack
      POSTGRES_PASSWORD: astackpass
      POSTGRES_DB: astackdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
