services:
  astack:
    build: .
    container_name: astack_app
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    tty: true
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: astack_db
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
